/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import AppPackage.AnimationClass;
import com.dao.DaoPersonals;
import com.dao.DaoUsers;
import com.pojos.Personals;
import com.pojos.Users;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfreding0
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    AnimationClass animationSlice = new AnimationClass();

    Personals personal = new Personals();
    DaoPersonals daoPersonals = new DaoPersonals();
    
    Users userAuth = null;
    
    Users user = new Users();
    DaoUsers daoUsers = new DaoUsers();

    public GUI() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        headerContent = new javax.swing.JPanel();
        btnMInimize = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        bodyContent = new javax.swing.JTabbedPane();
        homeLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        btnAnotaciones = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bntCronograma = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDrive = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnEventos = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnSocios = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        personalsIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddProduct = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnAddProduct1 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btnAddProduct4 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnAddProduct5 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        txtPersonalID = new javax.swing.JLabel();
        personalsForm = new javax.swing.JPanel();
        btnAddProduct2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btnAddProduct3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtPersonalCI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPersonalFirsName = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtPersonalLastName = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtPersonalPhone = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtPersonalAddress = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPersonalBirthday = new com.toedter.calendar.JDateChooser();
        sidebarContent = new javax.swing.JTabbedPane();
        sidebarLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JLabel();
        btnInternet = new javax.swing.JLabel();
        sidebarOptions = new javax.swing.JPanel();
        btnDrive5 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnDrive4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnDrive3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        btnDrive2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btnDrive1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnDrive6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(153, 153, 153));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setOpaque(true);
        background.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        headerContent.setBackground(new java.awt.Color(255, 255, 255));
        headerContent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 102, 0)));
        headerContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMInimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMInimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMInimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMInimizeMouseClicked(evt);
            }
        });
        headerContent.add(btnMInimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 30, 30));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Multiply_32px.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        headerContent.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 30));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Search_32px_2.png"))); // NOI18N
        headerContent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 30, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscar.setText("Buscar una opción");
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        headerContent.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 290, 30));

        background.add(headerContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, 110));

        bodyContent.setBackground(new java.awt.Color(255, 255, 255));
        bodyContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bodyContent.setForeground(new java.awt.Color(255, 255, 255));

        homeLogin.setBackground(new java.awt.Color(255, 255, 255));
        homeLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo-alf-services.png"))); // NOI18N
        homeLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, 140));

        jLabel25.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 102, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Alfred Services");
        homeLogin.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 730, 110));

        jLabel26.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 102, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("1");
        homeLogin.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 60, 110));

        jLabel34.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 102, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Desktop App #");
        homeLogin.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 710, 110));

        bodyContent.addTab("homeLogin", homeLogin);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnotaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnAnotaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnotaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnotacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnotacionesMouseExited(evt);
            }
        });
        btnAnotaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-customer-96.png"))); // NOI18N
        btnAnotaciones.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 90));

        jLabel16.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Anotaciones");
        btnAnotaciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnAnotaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 120, 150));

        btnAjustes.setBackground(new java.awt.Color(255, 255, 255));
        btnAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustesMouseExited(evt);
            }
        });
        btnAjustes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Maintenance_96px.png"))); // NOI18N
        btnAjustes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Settings");
        btnAjustes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 120, 150));

        bntCronograma.setBackground(new java.awt.Color(255, 255, 255));
        bntCronograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntCronogramaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntCronogramaMouseExited(evt);
            }
        });
        bntCronograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-staff-96.png"))); // NOI18N
        bntCronograma.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Personals");
        bntCronograma.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(bntCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 120, 150));

        btnDrive.setBackground(new java.awt.Color(255, 255, 255));
        btnDrive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDriveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDriveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDriveMouseExited(evt);
            }
        });
        btnDrive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-checked-user-male-96.png"))); // NOI18N
        btnDrive.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel18.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Users");
        btnDrive.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 150));

        btnEventos.setBackground(new java.awt.Color(255, 255, 255));
        btnEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEventosMouseExited(evt);
            }
        });
        btnEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-winter-sales-96.png"))); // NOI18N
        btnEventos.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 90));

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Sales");
        btnEventos.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 150));

        btnSocios.setBackground(new java.awt.Color(255, 255, 255));
        btnSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSociosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSociosMouseExited(evt);
            }
        });
        btnSocios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-multiple-devices-96.png"))); // NOI18N
        btnSocios.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel22.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Services");
        btnSocios.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 120, 150));

        bodyContent.addTab("Main", home);

        personalsIndex.setBackground(new java.awt.Color(255, 255, 255));
        personalsIndex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(24);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        personalsIndex.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 640, 320));

        btnAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProductMouseExited(evt);
            }
        });
        btnAddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ELIMINAR");
        btnAddProduct.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 130, 40));

        btnAddProduct1.setBackground(new java.awt.Color(255, 102, 51));
        btnAddProduct1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProduct1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProduct1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProduct1MouseExited(evt);
            }
        });
        btnAddProduct1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("AGREGAR");
        btnAddProduct1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnAddProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 40));

        btnAddProduct4.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduct4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnAddProduct4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProduct4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProduct4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProduct4MouseExited(evt);
            }
        });
        btnAddProduct4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 102, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("MOSTRAR");
        btnAddProduct4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnAddProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, 40));

        btnAddProduct5.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduct5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnAddProduct5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProduct5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProduct5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProduct5MouseExited(evt);
            }
        });
        btnAddProduct5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 102, 0));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("EDITAR");
        btnAddProduct5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnAddProduct5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, 40));

        txtPersonalID.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        txtPersonalID.setForeground(new java.awt.Color(153, 51, 0));
        txtPersonalID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPersonalID.setText("0");
        txtPersonalID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(204, 51, 0)));
        txtPersonalID.setFocusable(false);
        personalsIndex.add(txtPersonalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 40, 50, 40));

        bodyContent.addTab("Products", personalsIndex);

        personalsForm.setBackground(new java.awt.Color(255, 255, 255));
        personalsForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddProduct2.setBackground(new java.awt.Color(255, 102, 51));
        btnAddProduct2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProduct2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProduct2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProduct2MouseExited(evt);
            }
        });
        btnAddProduct2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("GUARDAR");
        btnAddProduct2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsForm.add(btnAddProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 130, 40));

        btnAddProduct3.setBackground(new java.awt.Color(255, 255, 255));
        btnAddProduct3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnAddProduct3.setForeground(new java.awt.Color(0, 0, 0));
        btnAddProduct3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProduct3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddProduct3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddProduct3MouseExited(evt);
            }
        });
        btnAddProduct3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 102, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("VOLVER");
        btnAddProduct3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsForm.add(btnAddProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 40));

        txtPersonalCI.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalCI.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalCI.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalCI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalCI.setText("Write here");
        txtPersonalCI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 290, 30));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("CI");
        personalsForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, -1));

        txtPersonalFirsName.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalFirsName.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalFirsName.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalFirsName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalFirsName.setText("Write here");
        txtPersonalFirsName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalFirsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 30));

        jLabel38.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 102, 0));
        jLabel38.setText("FIRST NAME");
        personalsForm.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, -1));

        txtPersonalLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalLastName.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalLastName.setText("Write here");
        txtPersonalLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 290, 30));

        jLabel39.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 102, 0));
        jLabel39.setText("LAST NAME");
        personalsForm.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 100, -1));

        txtPersonalPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalPhone.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalPhone.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalPhone.setText("Write here");
        txtPersonalPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 290, 30));

        jLabel40.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 102, 0));
        jLabel40.setText("PHONE");
        personalsForm.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, -1));

        txtPersonalAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalAddress.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalAddress.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalAddress.setText("Write here");
        txtPersonalAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 290, 30));

        jLabel41.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 102, 0));
        jLabel41.setText("ADDRESS");
        personalsForm.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 100, -1));

        jLabel42.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 102, 0));
        jLabel42.setText("BIRTHDAY");
        personalsForm.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        personalsForm.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 720, 10));

        txtPersonalBirthday.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalBirthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        txtPersonalBirthday.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        personalsForm.add(txtPersonalBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 249, 290, 30));

        bodyContent.addTab("Products", personalsForm);

        background.add(bodyContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 760, 510));

        sidebarLogin.setBackground(new java.awt.Color(255, 255, 255));
        sidebarLogin.setForeground(new java.awt.Color(255, 255, 255));
        sidebarLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_User_96px_2.png"))); // NOI18N
        sidebarLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, 100));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setText("Ingrese usuario");
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        sidebarLogin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 30));

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword.setText("jPasswordField1");
        txtpassword.setBorder(null);
        txtpassword.setOpaque(false);
        sidebarLogin.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 30));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        sidebarLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, 10));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        sidebarLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 150, 10));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Key_32px.png"))); // NOI18N
        sidebarLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 30, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("PASSWORD:");
        sidebarLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("USER:");
        sidebarLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));

        btnIngresar.setBackground(new java.awt.Color(255, 102, 51));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        btnIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INGRESAR");
        btnIngresar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        sidebarLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 140, 40));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_customer_32px_1.png"))); // NOI18N
        sidebarLogin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 30, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Menu_32px.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        sidebarLogin.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Globe_32px.png"))); // NOI18N
        btnInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInternetMouseClicked(evt);
            }
        });
        sidebarLogin.add(btnInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 60, 30, 30));

        sidebarContent.addTab("tab1", sidebarLogin);

        sidebarOptions.setBackground(new java.awt.Color(255, 255, 255));
        sidebarOptions.setForeground(new java.awt.Color(255, 255, 255));
        sidebarOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDrive5.setBackground(new java.awt.Color(255, 102, 0));
        btnDrive5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrive5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrive5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrive5MouseExited(evt);
            }
        });
        btnDrive5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Eventos");
        btnDrive5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnDrive5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, 40));

        btnDrive4.setBackground(new java.awt.Color(255, 102, 0));
        btnDrive4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrive4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrive4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrive4MouseExited(evt);
            }
        });
        btnDrive4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Productos");
        btnDrive4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnDrive4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 40));

        btnDrive3.setBackground(new java.awt.Color(255, 102, 0));
        btnDrive3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrive3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrive3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrive3MouseExited(evt);
            }
        });
        btnDrive3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Clientes");
        btnDrive3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnDrive3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 40));

        btnDrive2.setBackground(new java.awt.Color(255, 102, 0));
        btnDrive2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrive2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrive2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrive2MouseExited(evt);
            }
        });
        btnDrive2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Personals");
        btnDrive2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnDrive2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 40));

        btnDrive1.setBackground(new java.awt.Color(255, 102, 0));
        btnDrive1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrive1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrive1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrive1MouseExited(evt);
            }
        });
        btnDrive1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Home");
        btnDrive1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnDrive1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 40));

        btnDrive6.setBackground(new java.awt.Color(255, 102, 0));
        btnDrive6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrive6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrive6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDrive6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDrive6MouseExited(evt);
            }
        });
        btnDrive6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Ajustes");
        btnDrive6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnDrive6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, 40));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo-alf-services.png"))); // NOI18N
        sidebarOptions.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 160));

        sidebarContent.addTab("tab2", sidebarOptions);

        background.add(sidebarContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 10, 250, 580));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        userAuth = daoUsers.validateUserAndPassword(txtUsername.getText(), String.valueOf(txtpassword.getPassword()));
        if (userAuth != null) {
            sidebarContent.setSelectedComponent(sidebarOptions);
            bodyContent.setSelectedComponent(home);
        } else {
            sidebarContent.setSelectedComponent(sidebarLogin);
            bodyContent.setSelectedComponent(homeLogin);
            JOptionPane.showMessageDialog(null, "Your credentials are incorrect");
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        btnIngresar.setBackground(new Color(204, 51, 0));
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        btnIngresar.setBackground(new Color(255, 102, 51));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        animationSlice.jLabelXRight(-30, 10, 10, 5, btnInternet);
        animationSlice.jLabelXLeft(10, -30, 10, 5, btnInternet);
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnAnotacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnotacionesMouseEntered
        btnAnotaciones.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnAnotacionesMouseEntered

    private void btnAnotacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnotacionesMouseExited
        btnAnotaciones.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnAnotacionesMouseExited

    private void btnAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseEntered
        btnAjustes.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnAjustesMouseEntered

    private void btnAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseExited
        btnAjustes.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnAjustesMouseExited

    private void bntCronogramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCronogramaMouseEntered
        bntCronograma.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_bntCronogramaMouseEntered

    private void bntCronogramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCronogramaMouseExited
        bntCronograma.setBackground(Color.WHITE);
    }//GEN-LAST:event_bntCronogramaMouseExited

    private void btnDriveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDriveMouseEntered
        btnDrive.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnDriveMouseEntered

    private void btnDriveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDriveMouseExited
        btnDrive.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDriveMouseExited

    private void btnEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventosMouseEntered
        btnEventos.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnEventosMouseEntered

    private void btnEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventosMouseExited
        btnEventos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEventosMouseExited

    private void btnSociosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSociosMouseEntered
        btnSocios.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnSociosMouseEntered

    private void btnSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSociosMouseExited
        btnSocios.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSociosMouseExited

    private void btnMInimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMInimizeMouseClicked
        this.setState(GUI.ICONIFIED);
    }//GEN-LAST:event_btnMInimizeMouseClicked

    private void btnAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseClicked
        this.deletePersonal();
    }//GEN-LAST:event_btnAddProductMouseClicked

    private void btnAddProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProductMouseEntered

    private void btnAddProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProductMouseExited

    private void btnDriveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDriveMouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
    }//GEN-LAST:event_btnDriveMouseClicked

    private void btnInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInternetMouseClicked
        this.goToWebSiteEcosiaSearch();
    }//GEN-LAST:event_btnInternetMouseClicked

    private void btnDrive1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive1MouseClicked

    private void btnDrive1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive1MouseEntered

    private void btnDrive1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive1MouseExited

    private void btnDrive2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive2MouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
    }//GEN-LAST:event_btnDrive2MouseClicked

    private void btnDrive2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive2MouseEntered

    private void btnDrive2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive2MouseExited

    private void btnDrive3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive3MouseClicked

    private void btnDrive3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive3MouseEntered

    private void btnDrive3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive3MouseExited

    private void btnDrive4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive4MouseClicked

    private void btnDrive4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive4MouseEntered

    private void btnDrive4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive4MouseExited

    private void btnDrive5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive5MouseClicked

    private void btnDrive5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive5MouseEntered

    private void btnDrive5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive5MouseExited

    private void btnDrive6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive6MouseClicked

    private void btnDrive6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive6MouseEntered

    private void btnDrive6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrive6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrive6MouseExited

    private void btnAddProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct1MouseClicked
        this.clearPersonalFields();
        bodyContent.setSelectedComponent(personalsForm);
    }//GEN-LAST:event_btnAddProduct1MouseClicked

    private void btnAddProduct1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct1MouseEntered

    private void btnAddProduct1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct1MouseExited

    private void btnAddProduct2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct2MouseClicked
        if (txtPersonalID.getText().equals("0"))
            this.savePersonal();
        else
            this.updatePersonal();
    }//GEN-LAST:event_btnAddProduct2MouseClicked

    private void btnAddProduct2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct2MouseEntered

    private void btnAddProduct2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct2MouseExited

    private void btnAddProduct3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct3MouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
    }//GEN-LAST:event_btnAddProduct3MouseClicked

    private void btnAddProduct3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct3MouseEntered

    private void btnAddProduct3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct3MouseExited

    private void btnAddProduct4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct4MouseClicked
        this.listPersonals();
    }//GEN-LAST:event_btnAddProduct4MouseClicked

    private void btnAddProduct4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct4MouseEntered

    private void btnAddProduct4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct4MouseExited

    private void btnAddProduct5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct5MouseClicked
        bodyContent.setSelectedComponent(personalsForm);
    }//GEN-LAST:event_btnAddProduct5MouseClicked

    private void btnAddProduct5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct5MouseEntered

    private void btnAddProduct5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct5MouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.selectPersonal();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel bntCronograma;
    private javax.swing.JTabbedPane bodyContent;
    private javax.swing.JPanel btnAddProduct;
    private javax.swing.JPanel btnAddProduct1;
    private javax.swing.JPanel btnAddProduct2;
    private javax.swing.JPanel btnAddProduct3;
    private javax.swing.JPanel btnAddProduct4;
    private javax.swing.JPanel btnAddProduct5;
    private javax.swing.JPanel btnAjustes;
    private javax.swing.JPanel btnAnotaciones;
    private javax.swing.JPanel btnDrive;
    private javax.swing.JPanel btnDrive1;
    private javax.swing.JPanel btnDrive2;
    private javax.swing.JPanel btnDrive3;
    private javax.swing.JPanel btnDrive4;
    private javax.swing.JPanel btnDrive5;
    private javax.swing.JPanel btnDrive6;
    private javax.swing.JPanel btnEventos;
    private javax.swing.JPanel btnIngresar;
    private javax.swing.JLabel btnInternet;
    private javax.swing.JLabel btnMInimize;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel btnSocios;
    private javax.swing.JPanel headerContent;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homeLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel personalsForm;
    private javax.swing.JPanel personalsIndex;
    private javax.swing.JTabbedPane sidebarContent;
    private javax.swing.JPanel sidebarLogin;
    private javax.swing.JPanel sidebarOptions;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPersonalAddress;
    private com.toedter.calendar.JDateChooser txtPersonalBirthday;
    private javax.swing.JTextField txtPersonalCI;
    private javax.swing.JTextField txtPersonalFirsName;
    private javax.swing.JLabel txtPersonalID;
    private javax.swing.JTextField txtPersonalLastName;
    private javax.swing.JTextField txtPersonalPhone;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    private void goToWebSiteEcosiaSearch() {
        try {
            Desktop.getDesktop().browse(URI.create("www.ecosia.org"));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    private void openCalc() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.wait();
        } catch (IOException | InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

    private void openExplorer() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("explorer");
            p.wait();
        } catch (IOException | InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

    private void openVLC() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("vlc");
            p.wait();
        } catch (IOException | InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

    private void listPersonals() {
        List<Personals> personals = daoPersonals.getListPersonals();

        DefaultTableModel modelTable = new DefaultTableModel(
                null,
                new Object[]{"ID", "CI", "FIRSTNAME", "LASTNAME", "PHONE", "ADDRESS", "CREATEDAT"}
        );

        personals.forEach((value) -> {
            modelTable.addRow(new Object[]{value.getId(), value.getCi(), value.getFirstName(), value.getLastName(), value.getPhone(), value.getAddress(), value.getAddress()});
        });

        jTable1.setModel(modelTable);
    }

    private void savePersonal() {
        personal = new Personals(txtPersonalCI.getText(), txtPersonalFirsName.getText(), txtPersonalLastName.getText(), txtPersonalPhone.getText(), txtPersonalAddress.getText(), txtPersonalBirthday.getDate());
        daoPersonals.insert(personal);
        bodyContent.setSelectedComponent(personalsIndex);
        this.listPersonals();
    }

    private void selectPersonal() {
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            try {
                txtPersonalID.setText(jTable1.getValueAt(row, 0).toString());
                txtPersonalCI.setText(jTable1.getValueAt(row, 1).toString());
                txtPersonalFirsName.setText(jTable1.getValueAt(row, 2).toString());
                txtPersonalLastName.setText(jTable1.getValueAt(row, 3).toString());
                txtPersonalPhone.setText(jTable1.getValueAt(row, 4).toString());
                txtPersonalAddress.setText(jTable1.getValueAt(row, 5).toString());

                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(jTable1.getValueAt(row, 6).toString());
                txtPersonalBirthday.setDate(date);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }

    private void updatePersonal() {
        personal = new Personals(txtPersonalCI.getText(), txtPersonalFirsName.getText(), txtPersonalLastName.getText(), txtPersonalPhone.getText(), txtPersonalAddress.getText(), txtPersonalBirthday.getDate());
        personal.setId(Integer.parseInt(txtPersonalID.getText()));
        
        daoPersonals.update(personal);
        
        bodyContent.setSelectedComponent(personalsIndex);
        this.listPersonals();
    }

    private void clearPersonalFields() {
        txtPersonalID.setText("0");
        txtPersonalCI.setText("");
        txtPersonalFirsName.setText("");
        txtPersonalLastName.setText("");
        txtPersonalPhone.setText("");
        txtPersonalAddress.setText("");
        txtPersonalBirthday.setDate(new Date());
    }

    private void deletePersonal() {
        if (! txtPersonalID.getText().equals("0")){
            int response = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure to delete this record?");
            if (response == JOptionPane.YES_OPTION){
                personal = daoPersonals.find(Integer.parseInt(txtPersonalID.getText()));
                daoPersonals.delete(personal);
                
                txtPersonalID.setText("0");

                bodyContent.setSelectedComponent(personalsIndex);
                this.listPersonals();
            }
        } else
            javax.swing.JOptionPane.showMessageDialog(null, "You most select a row from the table");
    }

}
