/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.views;

import AppPackage.AnimationClass;
import com.alfreding0.utils.FieldsValidator;
import com.dao.DaoPersonals;
import com.dao.DaoUsers;
import com.pojos.Personals;
import com.pojos.Users;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.IOException;
import java.net.URI;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfreding0
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    AnimationClass animationSlice = new AnimationClass();

    Personals personal = new Personals();
    DaoPersonals daoPersonals = new DaoPersonals();
    
    Users userAuth = null;
    
    Users user = new Users();
    DaoUsers daoUsers = new DaoUsers();
    
    
    
    //COLORS
    Color darkOrange2 = new Color(255,102,51);
    Color darkOrange1 = new Color(255,128,86);
    Color lightOrange1 = new Color(250, 234, 223);
    Color lightOrange2 = new Color(250,134,112);
    Color iconOrange = new Color(255, 99, 71);
    

    public GUI() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setNewStyleHeaderTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        headerContent = new javax.swing.JPanel();
        btnMInimize = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        bodyContent = new javax.swing.JTabbedPane();
        homeLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        btnCustomers = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSetting = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPersonals = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnUsers = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSales = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnServices = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        personalsIndex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeletePersonal = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnAddPersonal = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btnShowPersonals = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnEditPersonal = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        txtPersonalID = new javax.swing.JLabel();
        personalsForm = new javax.swing.JPanel();
        btnSavePersonals = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btnBackPersonals = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtPersonalCI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPersonalFirsName = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtPersonalLastName = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtPersonalPhone = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtPersonalAddress = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPersonalBirthday = new com.toedter.calendar.JDateChooser();
        sidebarContent = new javax.swing.JTabbedPane();
        sidebarLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JLabel();
        btnInternet = new javax.swing.JLabel();
        sidebarOptions = new javax.swing.JPanel();
        btnUsersSidebar = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnServicesSidebar = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnCustomersSidebar = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        btnPersonalsSidebar = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnSalesSidebar = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(153, 153, 153));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 51, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Alf Services");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel24.setOpaque(true);
        background.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        headerContent.setBackground(new java.awt.Color(255, 237, 237));
        headerContent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 102, 0)));
        headerContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMInimize.setBackground(new java.awt.Color(255, 237, 237));
        btnMInimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMInimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMInimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMInimize.setOpaque(true);
        btnMInimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMInimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMInimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMInimizeMouseExited(evt);
            }
        });
        headerContent.add(btnMInimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 30, 30));

        btnSalir.setBackground(new java.awt.Color(255, 237, 237));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Multiply_32px.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setOpaque(true);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        headerContent.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 30));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Search_32px_2.png"))); // NOI18N
        headerContent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 30, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscar.setText("Buscar una opción");
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        headerContent.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 290, 30));

        lblTitle.setBackground(new java.awt.Color(255, 99, 71));
        lblTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 51, 0));
        lblTitle.setText(">Home");
        headerContent.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 30));

        background.add(headerContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, 110));

        bodyContent.setBackground(new java.awt.Color(255, 255, 255));
        bodyContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bodyContent.setForeground(new java.awt.Color(255, 255, 255));

        homeLogin.setBackground(new java.awt.Color(255, 255, 255));
        homeLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo-alf-services.png"))); // NOI18N
        homeLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, 140));

        jLabel25.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 99, 71));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Alfred Services");
        homeLogin.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 730, 110));

        jLabel26.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 102, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("1");
        homeLogin.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 60, 110));

        jLabel34.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 99, 71));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Desktop App #");
        homeLogin.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 710, 110));

        bodyContent.addTab("homeLogin", homeLogin);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCustomers.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomersMouseExited(evt);
            }
        });
        btnCustomers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-customer-96.png"))); // NOI18N
        btnCustomers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 90));

        jLabel16.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Customers");
        btnCustomers.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 120, 150));

        btnSetting.setBackground(new java.awt.Color(255, 255, 255));
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
        });
        btnSetting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Maintenance_96px.png"))); // NOI18N
        btnSetting.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Settings");
        btnSetting.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 120, 150));

        btnPersonals.setBackground(new java.awt.Color(255, 255, 255));
        btnPersonals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalsMouseExited(evt);
            }
        });
        btnPersonals.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-staff-96.png"))); // NOI18N
        btnPersonals.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Personals");
        btnPersonals.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnPersonals, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 120, 150));

        btnUsers.setBackground(new java.awt.Color(255, 255, 255));
        btnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsersMouseExited(evt);
            }
        });
        btnUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-checked-user-male-96.png"))); // NOI18N
        btnUsers.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel18.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Users");
        btnUsers.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 150));

        btnSales.setBackground(new java.awt.Color(255, 255, 255));
        btnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalesMouseExited(evt);
            }
        });
        btnSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-winter-sales-96.png"))); // NOI18N
        btnSales.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 90));

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Sales");
        btnSales.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 150));

        btnServices.setBackground(new java.awt.Color(255, 255, 255));
        btnServices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServicesMouseExited(evt);
            }
        });
        btnServices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-multiple-devices-96.png"))); // NOI18N
        btnServices.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 90));

        jLabel22.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Services");
        btnServices.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 20));

        home.add(btnServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 120, 150));

        bodyContent.addTab("Main", home);

        personalsIndex.setBackground(new java.awt.Color(255, 255, 255));
        personalsIndex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jTable1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setFocusable(false);
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(lightOrange1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        personalsIndex.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 640, 320));

        btnDeletePersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletePersonal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnDeletePersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletePersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletePersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletePersonalMouseExited(evt);
            }
        });
        btnDeletePersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("DELETE");
        btnDeletePersonal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnDeletePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 130, 40));

        btnAddPersonal.setBackground(new java.awt.Color(255, 102, 51));
        btnAddPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddPersonalMouseExited(evt);
            }
        });
        btnAddPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("ADD");
        btnAddPersonal.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnAddPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 40));

        btnShowPersonals.setBackground(new java.awt.Color(255, 255, 255));
        btnShowPersonals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnShowPersonals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowPersonals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPersonalsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShowPersonalsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShowPersonalsMouseExited(evt);
            }
        });
        btnShowPersonals.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 102, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("SHOW ALL");
        btnShowPersonals.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnShowPersonals, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, 40));

        btnEditPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnEditPersonal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnEditPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditPersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditPersonalMouseExited(evt);
            }
        });
        btnEditPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 102, 0));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("EDIT");
        btnEditPersonal.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsIndex.add(btnEditPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 130, 40));

        txtPersonalID.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        txtPersonalID.setForeground(new java.awt.Color(153, 51, 0));
        txtPersonalID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPersonalID.setText("0");
        txtPersonalID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(204, 51, 0)));
        txtPersonalID.setFocusable(false);
        personalsIndex.add(txtPersonalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 40, 50, 40));

        bodyContent.addTab("Products", personalsIndex);

        personalsForm.setBackground(new java.awt.Color(255, 255, 255));
        personalsForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSavePersonals.setBackground(new java.awt.Color(255, 102, 51));
        btnSavePersonals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSavePersonals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSavePersonalsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSavePersonalsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSavePersonalsMouseExited(evt);
            }
        });
        btnSavePersonals.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("SAVE");
        btnSavePersonals.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsForm.add(btnSavePersonals, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 130, 40));

        btnBackPersonals.setBackground(new java.awt.Color(255, 255, 255));
        btnBackPersonals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        btnBackPersonals.setForeground(new java.awt.Color(0, 0, 0));
        btnBackPersonals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackPersonals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackPersonalsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackPersonalsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackPersonalsMouseExited(evt);
            }
        });
        btnBackPersonals.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 102, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("BACK");
        btnBackPersonals.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        personalsForm.add(btnBackPersonals, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 40));

        txtPersonalCI.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalCI.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalCI.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalCI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalCI.setText("Write here");
        txtPersonalCI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 290, 30));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("CI");
        personalsForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, -1));

        txtPersonalFirsName.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalFirsName.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalFirsName.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalFirsName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalFirsName.setText("Write here");
        txtPersonalFirsName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalFirsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 30));

        jLabel38.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 102, 0));
        jLabel38.setText("FIRST NAME");
        personalsForm.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, -1));

        txtPersonalLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalLastName.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalLastName.setText("Write here");
        txtPersonalLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 290, 30));

        jLabel39.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 102, 0));
        jLabel39.setText("LAST NAME");
        personalsForm.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 100, -1));

        txtPersonalPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalPhone.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalPhone.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalPhone.setText("Write here");
        txtPersonalPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 290, 30));

        jLabel40.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 102, 0));
        jLabel40.setText("PHONE");
        personalsForm.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, -1));

        txtPersonalAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalAddress.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        txtPersonalAddress.setForeground(new java.awt.Color(102, 102, 102));
        txtPersonalAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPersonalAddress.setText("Write here");
        txtPersonalAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        personalsForm.add(txtPersonalAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 290, 30));

        jLabel41.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 102, 0));
        jLabel41.setText("ADDRESS");
        personalsForm.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 100, -1));

        jLabel42.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 102, 0));
        jLabel42.setText("BIRTHDAY");
        personalsForm.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        personalsForm.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 720, 10));

        txtPersonalBirthday.setBackground(new java.awt.Color(255, 255, 255));
        txtPersonalBirthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        txtPersonalBirthday.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        personalsForm.add(txtPersonalBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 249, 290, 30));

        bodyContent.addTab("Products", personalsForm);

        background.add(bodyContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 760, 510));

        sidebarLogin.setBackground(new java.awt.Color(255, 255, 255));
        sidebarLogin.setForeground(new java.awt.Color(255, 255, 255));
        sidebarLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_User_96px_2.png"))); // NOI18N
        sidebarLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, 100));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setText("alfreding0");
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        sidebarLogin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 30));

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword.setText("jPasswordField1");
        txtpassword.setBorder(null);
        txtpassword.setOpaque(false);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        sidebarLogin.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 30));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        sidebarLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, 10));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        sidebarLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 150, 10));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Key_32px.png"))); // NOI18N
        sidebarLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 30, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("PASSWORD:");
        sidebarLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("USER:");
        sidebarLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));

        btnLogIn.setBackground(new java.awt.Color(255, 102, 51));
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogInMouseExited(evt);
            }
        });
        btnLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LOG IN");
        btnLogIn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 130, -1));

        sidebarLogin.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 140, 40));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_customer_32px_1.png"))); // NOI18N
        sidebarLogin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 30, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Menu_32px.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        sidebarLogin.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_Globe_32px.png"))); // NOI18N
        btnInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInternetMouseClicked(evt);
            }
        });
        sidebarLogin.add(btnInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 60, 30, 30));

        sidebarContent.addTab("tab1", sidebarLogin);

        sidebarOptions.setBackground(new java.awt.Color(255, 255, 255));
        sidebarOptions.setForeground(new java.awt.Color(255, 255, 255));
        sidebarOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsersSidebar.setBackground(new java.awt.Color(255, 99, 71));
        btnUsersSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsersSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsersSidebarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsersSidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsersSidebarMouseExited(evt);
            }
        });
        btnUsersSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Users");
        btnUsersSidebar.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnUsersSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, 40));

        btnServicesSidebar.setBackground(new java.awt.Color(255, 99, 71));
        btnServicesSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServicesSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServicesSidebarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServicesSidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServicesSidebarMouseExited(evt);
            }
        });
        btnServicesSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Services");
        btnServicesSidebar.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnServicesSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 40));

        btnCustomersSidebar.setBackground(new java.awt.Color(255, 99, 71));
        btnCustomersSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomersSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomersSidebarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomersSidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomersSidebarMouseExited(evt);
            }
        });
        btnCustomersSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Customers");
        btnCustomersSidebar.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnCustomersSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 40));

        btnPersonalsSidebar.setBackground(new java.awt.Color(255, 99, 71));
        btnPersonalsSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonalsSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalsSidebarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalsSidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalsSidebarMouseExited(evt);
            }
        });
        btnPersonalsSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Personals");
        btnPersonalsSidebar.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnPersonalsSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 40));

        btnHome.setBackground(new java.awt.Color(255, 99, 71));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Home");
        btnHome.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 40));

        btnSalesSidebar.setBackground(new java.awt.Color(255, 99, 71));
        btnSalesSidebar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalesSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesSidebarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalesSidebarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalesSidebarMouseExited(evt);
            }
        });
        btnSalesSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Sales");
        btnSalesSidebar.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        sidebarOptions.add(btnSalesSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, 40));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo-alf-services.png"))); // NOI18N
        sidebarOptions.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 160));

        sidebarContent.addTab("tab2", sidebarOptions);

        background.add(sidebarContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 10, 250, 580));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseClicked
        this.userAuthentication();
    }//GEN-LAST:event_btnLogInMouseClicked

    private void btnLogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseEntered
        btnLogIn.setBackground(darkOrange1);
    }//GEN-LAST:event_btnLogInMouseEntered

    private void btnLogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseExited
        btnLogIn.setBackground(darkOrange2);
    }//GEN-LAST:event_btnLogInMouseExited

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        animationSlice.jLabelXRight(-30, 10, 10, 5, btnInternet);
        animationSlice.jLabelXLeft(10, -30, 10, 5, btnInternet);
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseEntered
        btnCustomers.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnCustomersMouseEntered

    private void btnCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseExited
        btnCustomers.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCustomersMouseExited

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        btnSetting.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        btnSetting.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSettingMouseExited

    private void btnPersonalsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalsMouseEntered
        btnPersonals.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnPersonalsMouseEntered

    private void btnPersonalsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalsMouseExited
        btnPersonals.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnPersonalsMouseExited

    private void btnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseEntered
        btnUsers.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnUsersMouseEntered

    private void btnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseExited
        btnUsers.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnUsersMouseExited

    private void btnSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseEntered
        btnSales.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnSalesMouseEntered

    private void btnSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseExited
        btnSales.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSalesMouseExited

    private void btnServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesMouseEntered
        btnServices.setBackground(new Color(250, 234, 223));
    }//GEN-LAST:event_btnServicesMouseEntered

    private void btnServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesMouseExited
        btnServices.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnServicesMouseExited

    private void btnMInimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMInimizeMouseClicked
        this.setState(GUI.ICONIFIED);
    }//GEN-LAST:event_btnMInimizeMouseClicked

    private void btnDeletePersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePersonalMouseClicked
        this.deletePersonal();
    }//GEN-LAST:event_btnDeletePersonalMouseClicked

    private void btnDeletePersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePersonalMouseEntered
        btnDeletePersonal.setBackground(lightOrange1);
    }//GEN-LAST:event_btnDeletePersonalMouseEntered

    private void btnDeletePersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePersonalMouseExited
        btnDeletePersonal.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDeletePersonalMouseExited

    private void btnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
    }//GEN-LAST:event_btnUsersMouseClicked

    private void btnInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInternetMouseClicked
        this.goToWebSiteEcosiaSearch();
    }//GEN-LAST:event_btnInternetMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        bodyContent.setSelectedComponent(home);
        lblTitle.setText(">Home");
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setBackground(lightOrange2);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBackground(iconOrange);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnPersonalsSidebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalsSidebarMouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
        this.listPersonals();
        lblTitle.setText(">Personal>Index");
    }//GEN-LAST:event_btnPersonalsSidebarMouseClicked

    private void btnPersonalsSidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalsSidebarMouseEntered
        btnPersonalsSidebar.setBackground(lightOrange2);
    }//GEN-LAST:event_btnPersonalsSidebarMouseEntered

    private void btnPersonalsSidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalsSidebarMouseExited
        btnPersonalsSidebar.setBackground(iconOrange);
    }//GEN-LAST:event_btnPersonalsSidebarMouseExited

    private void btnCustomersSidebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersSidebarMouseClicked
        
    }//GEN-LAST:event_btnCustomersSidebarMouseClicked

    private void btnCustomersSidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersSidebarMouseEntered
        btnCustomersSidebar.setBackground(lightOrange2);
    }//GEN-LAST:event_btnCustomersSidebarMouseEntered

    private void btnCustomersSidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersSidebarMouseExited
        btnCustomersSidebar.setBackground(iconOrange);
    }//GEN-LAST:event_btnCustomersSidebarMouseExited

    private void btnServicesSidebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesSidebarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServicesSidebarMouseClicked

    private void btnServicesSidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesSidebarMouseEntered
        btnServicesSidebar.setBackground(lightOrange2);
    }//GEN-LAST:event_btnServicesSidebarMouseEntered

    private void btnServicesSidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicesSidebarMouseExited
        btnServicesSidebar.setBackground(iconOrange);
    }//GEN-LAST:event_btnServicesSidebarMouseExited

    private void btnUsersSidebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersSidebarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersSidebarMouseClicked

    private void btnUsersSidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersSidebarMouseEntered
        btnUsersSidebar.setBackground(lightOrange2);
    }//GEN-LAST:event_btnUsersSidebarMouseEntered

    private void btnUsersSidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersSidebarMouseExited
        btnUsersSidebar.setBackground(iconOrange);
    }//GEN-LAST:event_btnUsersSidebarMouseExited

    private void btnSalesSidebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesSidebarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesSidebarMouseClicked

    private void btnSalesSidebarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesSidebarMouseEntered
        btnSalesSidebar.setBackground(lightOrange2);
    }//GEN-LAST:event_btnSalesSidebarMouseEntered

    private void btnSalesSidebarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesSidebarMouseExited
        btnSalesSidebar.setBackground(iconOrange);
    }//GEN-LAST:event_btnSalesSidebarMouseExited

    private void btnAddPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPersonalMouseClicked
        this.clearPersonalFields();
        bodyContent.setSelectedComponent(personalsForm);
        lblTitle.setText(">Personal>NewRecord");
    }//GEN-LAST:event_btnAddPersonalMouseClicked

    private void btnAddPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPersonalMouseEntered
        btnAddPersonal.setBackground(darkOrange1);
    }//GEN-LAST:event_btnAddPersonalMouseEntered

    private void btnAddPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPersonalMouseExited
        btnAddPersonal.setBackground(darkOrange2);
    }//GEN-LAST:event_btnAddPersonalMouseExited

    private void btnSavePersonalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavePersonalsMouseClicked
        if (FieldsValidator.isCompletedFields(new Object[]{txtPersonalCI, txtPersonalFirsName, txtPersonalLastName, txtPersonalPhone, txtPersonalAddress})){
            if (txtPersonalID.getText().equals("0"))
                this.savePersonal();
            else
                this.updatePersonal();

            lblTitle.setText(">Personal>Index");
        } else
            JOptionPane.showMessageDialog(null, "Complete all fields");
    }//GEN-LAST:event_btnSavePersonalsMouseClicked

    private void btnSavePersonalsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavePersonalsMouseEntered
        btnSavePersonals.setBackground(lightOrange2);
    }//GEN-LAST:event_btnSavePersonalsMouseEntered

    private void btnSavePersonalsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavePersonalsMouseExited
        btnSavePersonals.setBackground(darkOrange2);
    }//GEN-LAST:event_btnSavePersonalsMouseExited

    private void btnBackPersonalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPersonalsMouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
        lblTitle.setText(">Personal>Index");
    }//GEN-LAST:event_btnBackPersonalsMouseClicked

    private void btnBackPersonalsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPersonalsMouseEntered
        btnBackPersonals.setBackground(lightOrange1);
    }//GEN-LAST:event_btnBackPersonalsMouseEntered

    private void btnBackPersonalsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackPersonalsMouseExited
        btnBackPersonals.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnBackPersonalsMouseExited

    private void btnShowPersonalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPersonalsMouseClicked
        this.listPersonals();
    }//GEN-LAST:event_btnShowPersonalsMouseClicked

    private void btnShowPersonalsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPersonalsMouseEntered
        btnShowPersonals.setBackground(lightOrange1);
    }//GEN-LAST:event_btnShowPersonalsMouseEntered

    private void btnShowPersonalsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPersonalsMouseExited
        btnShowPersonals.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnShowPersonalsMouseExited

    private void btnEditPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPersonalMouseClicked
        bodyContent.setSelectedComponent(personalsForm);
        lblTitle.setText(">Personal>EditRecord");
    }//GEN-LAST:event_btnEditPersonalMouseClicked

    private void btnEditPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPersonalMouseEntered
        btnEditPersonal.setBackground(lightOrange1);
    }//GEN-LAST:event_btnEditPersonalMouseEntered

    private void btnEditPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPersonalMouseExited
        btnEditPersonal.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEditPersonalMouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.selectPersonal();
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        this.userAuthentication();
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnPersonalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalsMouseClicked
        bodyContent.setSelectedComponent(personalsIndex);
        this.listPersonals();
        lblTitle.setText(">Personal>Index");
    }//GEN-LAST:event_btnPersonalsMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(Color.RED);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(255,237,237));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMInimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMInimizeMouseEntered
        btnMInimize.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnMInimizeMouseEntered

    private void btnMInimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMInimizeMouseExited
        btnMInimize.setBackground(new Color(255,237,237));
    }//GEN-LAST:event_btnMInimizeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTabbedPane bodyContent;
    private javax.swing.JPanel btnAddPersonal;
    private javax.swing.JPanel btnBackPersonals;
    private javax.swing.JPanel btnCustomers;
    private javax.swing.JPanel btnCustomersSidebar;
    private javax.swing.JPanel btnDeletePersonal;
    private javax.swing.JPanel btnEditPersonal;
    private javax.swing.JPanel btnHome;
    private javax.swing.JLabel btnInternet;
    private javax.swing.JPanel btnLogIn;
    private javax.swing.JLabel btnMInimize;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JPanel btnPersonals;
    private javax.swing.JPanel btnPersonalsSidebar;
    private javax.swing.JPanel btnSales;
    private javax.swing.JPanel btnSalesSidebar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel btnSavePersonals;
    private javax.swing.JPanel btnServices;
    private javax.swing.JPanel btnServicesSidebar;
    private javax.swing.JPanel btnSetting;
    private javax.swing.JPanel btnShowPersonals;
    private javax.swing.JPanel btnUsers;
    private javax.swing.JPanel btnUsersSidebar;
    private javax.swing.JPanel headerContent;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homeLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel personalsForm;
    private javax.swing.JPanel personalsIndex;
    private javax.swing.JTabbedPane sidebarContent;
    private javax.swing.JPanel sidebarLogin;
    private javax.swing.JPanel sidebarOptions;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPersonalAddress;
    private com.toedter.calendar.JDateChooser txtPersonalBirthday;
    private javax.swing.JTextField txtPersonalCI;
    private javax.swing.JTextField txtPersonalFirsName;
    private javax.swing.JLabel txtPersonalID;
    private javax.swing.JTextField txtPersonalLastName;
    private javax.swing.JTextField txtPersonalPhone;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    private void goToWebSiteEcosiaSearch() {
        try {
            Desktop.getDesktop().browse(URI.create("www.ecosia.org"));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    private void openCalc() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.wait();
        } catch (IOException | InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

    private void openExplorer() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("explorer");
            p.wait();
        } catch (IOException | InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

    private void openVLC() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("vlc");
            p.wait();
        } catch (IOException | InterruptedException e) {
            System.out.println(e.getMessage());
        }
    }

    private void listPersonals() {
        List<Personals> personals = daoPersonals.getListPersonals();

        DefaultTableModel modelTable = new DefaultTableModel(
                null,
                new Object[]{"ID", "CI", "FIRSTNAME", "LASTNAME", "PHONE", "ADDRESS", "BIRTHDAY"}
        );

        personals.forEach((value) -> {
            modelTable.addRow(new Object[]{value.getId(), value.getCi(), value.getFirstName(), value.getLastName(), value.getPhone(), value.getAddress(), value.getBirthday()});
        });

        jTable1.setModel(modelTable);
    }

    private void savePersonal() {
        personal = new Personals(txtPersonalCI.getText(), txtPersonalFirsName.getText(), txtPersonalLastName.getText(), txtPersonalPhone.getText(), txtPersonalAddress.getText(), txtPersonalBirthday.getDate());
        daoPersonals.insert(personal);
        bodyContent.setSelectedComponent(personalsIndex);
        this.listPersonals();
    }

    private void selectPersonal() {
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            try {
                txtPersonalID.setText(jTable1.getValueAt(row, 0).toString());
                txtPersonalCI.setText(jTable1.getValueAt(row, 1).toString());
                txtPersonalFirsName.setText(jTable1.getValueAt(row, 2).toString());
                txtPersonalLastName.setText(jTable1.getValueAt(row, 3).toString());
                txtPersonalPhone.setText(jTable1.getValueAt(row, 4).toString());
                txtPersonalAddress.setText(jTable1.getValueAt(row, 5).toString());

                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(jTable1.getValueAt(row, 6).toString());
                txtPersonalBirthday.setDate(date);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }

    private void updatePersonal() {
        personal = new Personals(txtPersonalCI.getText(), txtPersonalFirsName.getText(), txtPersonalLastName.getText(), txtPersonalPhone.getText(), txtPersonalAddress.getText(), txtPersonalBirthday.getDate());
        personal.setId(Integer.parseInt(txtPersonalID.getText()));
        
        daoPersonals.update(personal);
        
        bodyContent.setSelectedComponent(personalsIndex);
        this.listPersonals();
    }

    private void clearPersonalFields() {
        txtPersonalID.setText("0");
        txtPersonalCI.setText("");
        txtPersonalFirsName.setText("");
        txtPersonalLastName.setText("");
        txtPersonalPhone.setText("");
        txtPersonalAddress.setText("");
        txtPersonalBirthday.setDate(new Date());
    }

    private void deletePersonal() {
        if (! txtPersonalID.getText().equals("0")){
            int response = javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure to delete this record?");
            if (response == JOptionPane.YES_OPTION){
                personal = daoPersonals.find(Integer.parseInt(txtPersonalID.getText()));
                daoPersonals.delete(personal);
                
                txtPersonalID.setText("0");

                bodyContent.setSelectedComponent(personalsIndex);
                this.listPersonals();
            }
        } else
            javax.swing.JOptionPane.showMessageDialog(null, "You most select a row from the table");
    }

    private void userAuthentication() {
        userAuth = daoUsers.validateUserAndPassword(txtUsername.getText(), String.valueOf(txtpassword.getPassword()));
        if (userAuth != null) {
            sidebarContent.setSelectedComponent(sidebarOptions);
            bodyContent.setSelectedComponent(home);
        } else {
            sidebarContent.setSelectedComponent(sidebarLogin);
            bodyContent.setSelectedComponent(homeLogin);
            JOptionPane.showMessageDialog(null, "Your credentials are incorrect");
        }
    }

    private void setNewStyleHeaderTable() {
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jTable1.getTableHeader().setBackground(darkOrange1);
        jTable1.getTableHeader().setFont(new Font("Corbel", Font.BOLD, 14));
    }

}
