package com.pojos;
// Generated Jul 15, 2022 5:26:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers",
         schema = "public"
)
public class Customers implements java.io.Serializable {

    private int id;
    private String ci;
    private String firstName;
    private String lastName;
    private String phone;
    private Date createdAt;
    private Date updatedAt;
    private Set<Sales> saleses = new HashSet<Sales>(0);

    public Customers() {
    }

    public Customers(int id, String ci, String firstName, String lastName, String phone) {
        this.id = id;
        this.ci = ci;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
    }

    public Customers(int id, String ci, String firstName, String lastName, String phone, Date createdAt, Date updatedAt, Set<Sales> saleses) {
        this.id = id;
        this.ci = ci;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.saleses = saleses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "ci", nullable = false, length = 12)
    public String getCi() {
        return this.ci;
    }

    public void setCi(String ci) {
        this.ci = ci;
    }

    @Column(name = "first_name", nullable = false, length = 50)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", nullable = false, length = 50)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "phone", nullable = false, length = 20)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", length = 29)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", length = 29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
    public Set<Sales> getSaleses() {
        return this.saleses;
    }

    public void setSaleses(Set<Sales> saleses) {
        this.saleses = saleses;
    }

}
