package com.pojos;
// Generated Jul 15, 2022 5:26:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personals generated by hbm2java
 */
@Entity
@Table(name="personals"
    ,schema="public"
)
public class Personals  implements java.io.Serializable {


     private int id;
     private String ci;
     private String firstName;
     private String lastName;
     private String phone;
     private String address;
     private Date birthday;
     private Date createdAt;
     private Date updatedAt;
     private Set<Sales> saleses = new HashSet<Sales>(0);
     private Set<Users> userses = new HashSet<Users>(0);

    public Personals() {
    }

	
    public Personals(int id, String ci, String firstName, String lastName, String phone, String address, Date birthday) {
        this.id = id;
        this.ci = ci;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.address = address;
        this.birthday = birthday;
    }
    public Personals(int id, String ci, String firstName, String lastName, String phone, String address, Date birthday, Date createdAt, Date updatedAt, Set<Sales> saleses, Set<Users> userses) {
       this.id = id;
       this.ci = ci;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.address = address;
       this.birthday = birthday;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.saleses = saleses;
       this.userses = userses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ci", nullable=false, length=12)
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone", nullable=false, length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", nullable=false, length=13)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personals")
    public Set<Sales> getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set<Sales> saleses) {
        this.saleses = saleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personals")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


