package com.pojos;
// Generated Jul 15, 2022 5:26:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sales generated by hbm2java
 */
@Entity
@Table(name="sales"
    ,schema="public"
)
public class Sales  implements java.io.Serializable {


     private int id;
     private Customers customers;
     private Personals personals;
     private Date dateTime;
     private double total;
     private Date createdAt;
     private Date updatedAt;
     private Set<SalesServices> salesServiceses = new HashSet<SalesServices>(0);

    public Sales() {
    }

	
    public Sales(int id, Customers customers, Personals personals, Date dateTime, double total) {
        this.id = id;
        this.customers = customers;
        this.personals = personals;
        this.dateTime = dateTime;
        this.total = total;
    }
    public Sales(int id, Customers customers, Personals personals, Date dateTime, double total, Date createdAt, Date updatedAt, Set<SalesServices> salesServiceses) {
       this.id = id;
       this.customers = customers;
       this.personals = personals;
       this.dateTime = dateTime;
       this.total = total;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.salesServiceses = salesServiceses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="personal_id", nullable=false)
    public Personals getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Personals personals) {
        this.personals = personals;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_time", nullable=false, length=29)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    
    @Column(name="total", nullable=false, precision=17, scale=17)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sales")
    public Set<SalesServices> getSalesServiceses() {
        return this.salesServiceses;
    }
    
    public void setSalesServiceses(Set<SalesServices> salesServiceses) {
        this.salesServiceses = salesServiceses;
    }




}


