package com.pojos;
// Generated Jul 15, 2022 5:26:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name="services"
    ,schema="public"
)
public class Services  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private double price;
     private Date createdAt;
     private Date updatedAt;
     private Set<SalesServices> salesServiceses = new HashSet<SalesServices>(0);

    public Services() {
    }

	
    public Services(int id, String name, double price) {
        this.id = id;
        this.name = name;
        this.price = price;
    }
    public Services(int id, String name, String description, double price, Date createdAt, Date updatedAt, Set<SalesServices> salesServiceses) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.price = price;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.salesServiceses = salesServiceses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=17, scale=17)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<SalesServices> getSalesServiceses() {
        return this.salesServiceses;
    }
    
    public void setSalesServiceses(Set<SalesServices> salesServiceses) {
        this.salesServiceses = salesServiceses;
    }




}


