package com.pojos;
// Generated Jul 15, 2022 5:26:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,schema="public"
)
public class Users  implements java.io.Serializable {


     private int id;
     private Personals personals;
     private String name;
     private String email;
     private String password;
     private Date createdAt;
     private Date updatedAt;

    public Users() {
    }

	
    public Users(int id, Personals personals, String name, String email, String password) {
        this.id = id;
        this.personals = personals;
        this.name = name;
        this.email = email;
        this.password = password;
    }
    public Users(int id, Personals personals, String name, String email, String password, Date createdAt, Date updatedAt) {
       this.id = id;
       this.personals = personals;
       this.name = name;
       this.email = email;
       this.password = password;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="personal_id", nullable=false)
    public Personals getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Personals personals) {
        this.personals = personals;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


